### ISSUE TITLE
Feature: Metrics by containers

### ISSUE THREAD

**Issue by deepu105** [davidB/kubectl-view-allocations#139]
I was reading up on [this](https://www.replex.io/blog/kubernetes-in-production-the-ultimate-guide-to-monitoring-resource-metrics) and thought it would be interesting to see utilization by containers as well along with pods, namespace and nodes.

What do you think? if you think its good then I can work on it and do a PR. Should be straightforward since the pod metrics should have data by containers already

**Comment by davidB** [comment]
I'll read the article, currently TBH, I don't know, because:

- utilization is only available/measure for CPU & memory
- how to show containers level for every kind of allocatable
- how to display container  (name of the container, init, status,???)

But until I found the usage in the cli, I'm open to enhance the lib side of the crates (refactor, expose useful functions for other,...). So ok for a PR.

Thanks

**Comment by davidB** [comment]
I close the ticket, but feel free to reopen with idea, proposal (cli args, output,), code, ou to proviode a PR.
